version: '3.7'

services:
  app:
    image: node:alpine
    user: node
    working_dir: /home/node/app
    volumes: 
      -  .:/home/node/app
    ports: 
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - db

  db: 
    image: mysql:debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nest_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./db/conf:/docker-entrypoint-initdb.d
      - ./db/vol:/var/lib/mysql
    ports:
      - 3306:3306
